### ISSUE TITLE
ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument: Instance of 'Status'

### ISSUE THREAD

**Issue by jhonvegamas** [claimsforce-gmbh/flutter-segment#51]
E/flutter (14273): [ERROR:flutter/lib/ui/ui_dart_state.cc(177)] Unhandled Exception: Invalid argument: Instance of 'Status'
E/flutter (14273): #0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:404:7)
E/flutter (14273): #1      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:401:9)
E/flutter (14273): #2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (14273): #3      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:399:13)
E/flutter (14273): #4      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:401:9)
E/flutter (14273): #5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
E/flutter (14273): #6      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:399:13)
E/flutter (14273): #7      StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:536:18)
E/flutter (14273): #8      MethodChannel._invokeMethod (package:flutter/src/services/platform_channel.dart:151:13)
E/flutter (14273): #9      MethodChannel.invokeMethod (package:flutter/src/services/platform_channel.dart:332:12)
E/flutter (14273): #10     SegmentMethodChannel.identify (package:flutter_segment/src/segment_method_channel.dart:15:22)
E/flutter (14273): #11     Segment.identify (package:flutter_segment/src/segment.dart:17:21)
E/flutter (14273): #12     _SegmentService.identify (package:famosos/services/segment_service.dart:31:15)
E/flutter (14273): #13     _LauncherPageState.build (package:famosos/pages/auth/launcher_page.dart:48:22)
E/flutter (14273): #14     StatefulElement.build (package:flutter/src/widgets/framework.dart:4744:28)
E/flutter (14273): #15     ComponentElement.performRebuild (package:flutter/src/widgets/framework.dart:4627:15)
E/flutter (14273): #16     StatefulElement.performRebuild (package:flutter/src/widgets/framework.dart:4800:11)
E/flutter (14273): #17     Element.rebuild (package:flutter/src/widgets/framework.dart:4343:5)
E/flutter (14273): #18     BuildOwner.buildScope (package:flutter/src/widgets/framework.dart:2730:33)
E/flutter (14273): #19     WidgetsBinding.drawFrame (package:flutter/src/widgets/binding.dart:913:20)
E/flutter (14273): #20     RendererBinding._handlePersistentFrameCallback (package:flutter/src/rendering/binding.dart:302:5)
E/flutter (14273): #21     SchedulerBinding._invokeFrameCallback (package:flutter/src/scheduler/binding.dart:1117:15)
E/flutter (14273): #22     SchedulerBinding.handleDrawFrame (package:flutter/src/scheduler/binding.dart:1055:9)
E/flutter (14273): #23     SchedulerBinding._handleDrawFrame (package:flutter/src/scheduler/binding.dart:971:5)
E/flutter (14273): #24     _rootRun (dart:async/zone.dart:1190:13)
E/flutter (14273): #25     _CustomZone.run (dart:async/zone.dart:1093:19)
E/flutter (14273): #26     _CustomZone.runGuarded (dart:async/zone.dart:997:7)
E/flutter (14273): #27     _invoke (dart:ui/hooks.dart:251:10)
E/flutter (14273): #28     _drawFrame (dart:ui/hooks.dart:209:3)
E/flutter (14273): 

Error in Segment.identify(userId: id, traits: traits);

Segment.track and Segment.screen work well just identify failure

**Comment by jhonvegamas** [comment]
Be careful with the additional parameters, if you have a model in another model make sure you are sending strings or int to avoid problems
