### ISSUE TITLE
Crash after sending bad properties for events 

### ISSUE THREAD

**Issue by danielgomezrico** [claimsforce-gmbh/flutter-segment#62]
After you send bad properties the Segment SDK on android throws an exception that is not been handled by the library and so the Flutter code can not handle it.

# Example
```dart
Segment.track('any', { MapEntry('something': 'other') })
```

# Stacktrace
```dart
/flutter (10715): Invalid argument: Instance of 'MappedListIterable<MapEntry, Map<String, dynamic>>'
I/flutter (10715): 	#0      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:404:7)
I/flutter (10715): 	#1      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:401:9)
I/flutter (10715): 	#2      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
I/flutter (10715): 	#3      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:399:13)
I/flutter (10715): 	#4      StandardMessageCodec.writeValue.<anonymous closure> (package:flutter/src/services/message_codecs.dart:401:9)
I/flutter (10715): 	#5      _LinkedHashMapMixin.forEach (dart:collection-patch/compact_hash.dart:377:8)
I/flutter (10715): 	#6      StandardMessageCodec.writeValue (package:flutter/src/services/message_codecs.dart:399:13)
I/flutter (10715): 	#7      StandardMethodCodec.encodeMethodCall (package:flutter/src/services/message_codecs.dart:536:18)
I/flutter (10715): 	#8      MethodChannel._invokeMethod (package:flutter/src/servi
```

**Comment by MaiKaY** [comment]
Hi @danielgomezrico, could you please upgrade to `3.1.2` and check if this crash still remains?

**Comment by danielgomezrico** [comment]
@MaiKaY we are in the middle of migrating to flutter 2, I will test it after we are done with that, thanks :)

**Comment by MaiKaY** [comment]
@danielgomezrico does the issue still exists?
