### ISSUE TITLE
`v3.4.1` Immediately crashes the Android `release` on startup.

### ISSUE THREAD

**Issue by EhabSalah** [claimsforce-gmbh/flutter-segment#98]
## Crash on Android `release` startup.

In Android everything is working fine in debug mode, but immediately crash on release mode startup!.

 > flutter sdk version 2.5.3
 flutter_segment version 3.4.1

```
E/FlutterSegment(19504): Attempt to invoke interface method 'int java.lang.CharSequence.length()' on a null object reference
I/FlutterSegment(19504): Lifecycle events are not been tracked
E/AndroidRuntime(19504): FATAL EXCEPTION: main
E/AndroidRuntime(19504): Process: com.companyname.app, PID: 19504
E/AndroidRuntime(19504): java.lang.IllegalAccessError: Interface androidx.lifecycle.e implemented by class com.segment.analytics.AnalyticsActivityLifecycleCallbacks is inaccessible (declaration of 'com.segment.analytics.AnalyticsActivityLifecycleCallbacks' appears in /data/app/~~DiPrYhrEK1yFTREU3QRAEA==/com.companyname.app-7wTt_NaPmzW5k2y9imp_XA==/base.apk)
E/AndroidRuntime(19504):        at com.segment.analytics.AnalyticsActivityLifecycleCallbacks$b.c(Unknown Source:0)
E/AndroidRuntime(19504):        at com.segment.analytics.a.<init>(Unknown Source:166)
E/AndroidRuntime(19504):        at com.segment.analytics.a$l.a(Unknown Source:341)
E/AndroidRuntime(19504):        at f.c.a.b.s(Unknown Source:75)
E/AndroidRuntime(19504):        at f.c.a.b.i(Unknown Source:12)
E/AndroidRuntime(19504):        at f.c.a.b.onMethodCall(Unknown Source:10)
E/AndroidRuntime(19504):        at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(Unknown Source:17)
E/AndroidRuntime(19504):        at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(Unknown Source:49)
E/AndroidRuntime(19504):        at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(Unknown Source:4)
E/AndroidRuntime(19504):        at android.os.MessageQueue.nativePollOnce(Native Method)
E/AndroidRuntime(19504):        at android.os.MessageQueue.next(MessageQueue.java:335)
E/AndroidRuntime(19504):        at android.os.Looper.loop(Looper.java:206)
E/AndroidRuntime(19504):        at android.app.ActivityThread.main(ActivityThread.java:8506)
E/AndroidRuntime(19504):        at java.lang.reflect.Method.invoke(Native Method)
E/AndroidRuntime(19504):        at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:602)
E/AndroidRuntime(19504):        at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1130)
```

**Comment by danielgomezrico** [comment]
@EhabSalah do you have proguard in your android side?

**Comment by Rostyslav91** [comment]
@EhabSalah Hi, change in android/build.gradle next line

classpath 'com.android.tools.build:gradle:4.1.0'

to 

classpath 'com.android.tools.build:gradle:3.6.2'

**Comment by omzer** [comment]
Can you ensure that you are not using the deprecated way of initializing segment? (by adding  `<meta-data` tags to the manifest)

**Comment by omzer** [comment]
@MaiKaY any idea how to solve this? it makes the whole library unusable.

Not sure if it helps, but running on android version shows the following error:
```Note: /Users/omar/Desktop/3mr/programs/flutter/.pub-cache/hosted/pub.dartlang.org/flutter_segment-3.5.0/android/src/main/java/com/example/flutter_segment/FlutterSegmentPlugin.java uses or overrides a deprecated API.
Note: Recompile with -Xlint:deprecation for details.
Note: Some input files use unchecked or unsafe operations.
Note: Recompile with -Xlint:unchecked for details.
```

**Comment by MaiKaY** [comment]
@ariefwijaya do you have an idea and could support here?

**Comment by danielgomezrico** [comment]
I cant reproduce it in `3.5.0` @EhabSalah do you have an example project showing that it explodes?

**Comment by EhabSalah** [comment]
@danielgomezrico I have just realized that as am setting my own proguard rules, I also have to tell him to [keep segment classes](https://segment.com/docs/connections/sources/catalog/libraries/mobile/android/android-faqs/#how-should-i-configure-proguard).

> By adding this snippet to `android/app/proguard-rules.pro`
```
-keep class com.segment.analytics.** { *; }
-keep class androidx.lifecycle.DefaultLifecycleObserver
```
